# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
dist: xenial
env:
  PYTHON: ""
os:
  - linux
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
      - julia: nightly
  fast_finish: true
notifications:
  email: false
